dist: trusty
language: java
jdk:
   -openjdk8
addons:
  apt:
    packages:
      - ant
script: ant build

addons:
  sonarcloud:
    organization: "michelalattanzi"
    token:
      secure: "db1ff793898d213acfb7b7160cc3d0e3bc5bcb93"

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - sonar-scanner
